# Umfpack lib usually requires linking to a blas library.
# It is up to the user of this module to find a BLAS and link to it.

find_path(UMFPACK_INCLUDE_DIRS
  NAMES
  umfpack.h
  PATHS
  ${UMFPACK_DIR}/include
  ${UMFPACK_DIR}/include/suitesparse
  NO_DEFAULT_PATH
)

message("UMFPACK_DIR: " "${UMFPACK_DIR}")
message("UMFPACK_INCLUDE_DIRS: " "${UMFPACK_INCLUDE_DIRS}")

find_library(UMFPACK_LIBRARIES umfpack PATHS ${UMFPACK_DIR}/lib NO_DEFAULT_PATH)

if(UMFPACK_LIBRARIES)

  if (NOT UMFPACK_LIBDIR)
    get_filename_component(UMFPACK_LIBDIR ${UMFPACK_LIBRARIES} PATH)
  endif(NOT UMFPACK_LIBDIR)

  find_library(CHOLMOD_LIBRARY cholmod PATHS ${UMFPACK_LIBDIR} ${UMFPACK_DIR} NO_DEFAULT_PATH)
  if (CHOLMOD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${CHOLMOD_LIBRARY})
  endif (CHOLMOD_LIBRARY)

  find_library(COLAMD_LIBRARY colamd PATHS ${UMFPACK_LIBDIR} ${UMFPACK_DIR} NO_DEFAULT_PATH)
  if (COLAMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${COLAMD_LIBRARY})
  endif (COLAMD_LIBRARY)

  find_library(CCOLAMD_LIBRARY ccolamd PATHS ${UMFPACK_LIBDIR} ${UMFPACK_DIR} NO_DEFAULT_PATH)
  if (CCOLAMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${CCOLAMD_LIBRARY})
  endif (CCOLAMD_LIBRARY)

  find_library(AMD_LIBRARY amd PATHS ${UMFPACK_LIBDIR} ${UMFPACK_DIR} NO_DEFAULT_PATH)
  if (AMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${AMD_LIBRARY})
  endif (AMD_LIBRARY)

  find_library(CAMD_LIBRARY camd PATHS ${UMFPACK_LIBDIR} ${UMFPACK_DIR} NO_DEFAULT_PATH)
  if (CAMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${CAMD_LIBRARY})
  endif (CAMD_LIBRARY)

#  find_library(METIS_LIBRARY metis PATHS ${UMFPACK_LIBDIR} ${UMFPACK_DIR} NO_DEFAULT_PATH)
#  if (METIS_LIBRARY)
#    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${METIS_LIBRARY})
#  endif (METIS_LIBRARY)

  find_library(SUITESPARSE_LIBRARY suitesparseconfig PATHS ${UMFPACK_LIBDIR} ${UMFPACK_DIR} NO_DEFAULT_PATH)
  if (SUITESPARSE_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${SUITESPARSE_LIBRARY})
  endif (SUITESPARSE_LIBRARY)

endif(UMFPACK_LIBRARIES)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(UMFPACK DEFAULT_MSG UMFPACK_INCLUDE_DIRS UMFPACK_LIBRARIES)

mark_as_advanced(UMFPACK_INCLUDE_DIRS UMFPACK_LIBRARIES AMD_LIBRARY COLAMD_LIBRARY SUITESPARSE_LIBRARY)
